### ISSUE TITLE
How to remove LazyLoading from thiss theme?

### ISSUE THREAD

**Issue by jmj4you** [codetok/cdk-admin#14]
Hi,
Could you please let me know how to remove lazy loading from this Angular theme.

Thanks

**Comment by harikrishna266** [comment]
thats one of the core feature of angular, why do you want to remove it?
if you look at lazyloader.routes.ts inside auth folder, the  DashboardCrmComponent is not not lazy loaded.

**Comment by jmj4you** [comment]
Thank you for kind reply :)
When I click for next link/components its getting too delay, So i don't like it... :(

**Comment by harikrishna266** [comment]
I agree that there is a delay when you click on links that are lazy loaded. (especially material widgets)
This is because i have lazy loaded all that into one module, and in my case all the html needs to be pulled from the server before it can show. 
In real world scenarios, you don't have so much of HTML to pull from server and you make smaller modules that are lazy loaded. So that should be fine.
